import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'fr' | 'rw' | 'es' | 'zh' | 'de' | 'hi' | 'ar' | 'pt' | 'ja' | 'ru';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header & General Navigation
    overview: 'Overview',
    tradeTab: 'Global Trade',
    liveMap: 'Live Map & Tours',
    resourceProjects: 'Resource Projects',
    esgSafety: 'ESG & Safety',
    geologicalLibrary: 'Geological Library',
    investorRelations: 'Investor Relations',
    inquireTerminal: 'Inquire Terminal',
    qualifyAccess: 'QUALIFIER FOR ACCESS',
    liveIndex: 'Live LME/NYMEX Mineral Index:',
    companyTitle: 'MineX Gold, Silver & Bronze',
    companySubtitle: 'Strategic Gold, Silver & Bronze Operations',

    // Hero Section
    heroTitlePre: 'Autonomous scale.',
    heroTitlePost: 'Sovereign supply.',
    heroSubtitle: 'MineX is a tier-one resource champion producing gold, silver, bronze, high-purity copper concentrates, and low-footprint lithium across highly stable OECD jurisdictions.',
    exploreProjectsButton: 'Explore Asset Portfolio',
    secureAccessButton: 'Secure Geo-Data Access',
    activeConcessions: 'Active Concessions',
    combinedReserves: 'Combined Reserves',
    esgCarbonSc: 'ESG Carbon Score',
    annualTarget: 'Annual Target Gold',
    investorPortal: 'Institutional Investor Portal',
    partnerPortal: 'Corporate Offtake & Smelter Partners',
    governmentPortal: 'Sovereign Governments & Environment',
    verifyRegistry: 'Verify Global Asset Registry',
    submitSpecSheets: 'Submit Metallurgy Specifications',
    inspectEsgPiles: 'Inspect Environmental Accreditation',

    // Landing Subsections Block
    tierOneCapital: 'Tier-One Capital Focus',
    tierOneCapitalDesc: 'We operate exclusively in stable, democratic OECD-compliant mining jurisdictions, guaranteeing raw metal supply chains against regional political conflicts.',
    tierOneCapitalAction: 'Verify Jurisdictions',
    lowCarbonPath: 'Traceable Low Carbon Path',
    lowCarbonPathDesc: 'From solar grid matching to fully electrified underground loader operations, we supply premium grade concentrates backed by traceable carbon audits.',
    lowCarbonPathAction: 'Inspect ESG Targets',
    institutionalScale: 'Qualified Institutional Scale',
    institutionalScaleDesc: 'Our deposit sites represent over 22.4M oz gold equivalent in combined reserves, proven by core drilling assay tables open to validated research teams.',
    institutionalScaleAction: 'Search Geologic Desk',

    // Concessions Map & Site Tour Tracker
    operationsTitle: 'Real-Time Assets & Telemetries',
    operationsHeader: 'Interactive Map',
    operationsHeaderPost: ' & Mine Tours',
    operationsDesc: 'Verify global activities on the ground. Drill down into our active concessions or launch virtual 360° tours of our mine drifts, assay labs, and extraction chambers.',
    tabLiveMap: 'Live Operations Map',
    tabVirtualTour: '360° Virtual Site Tour',
    satCoordinateSys: 'SATELLITE POSITION COORDINATE SYSTEM',
    liveGpsStream: 'Live GPS Stream Active',
    concessionHub: 'CONCESSION HUB',
    telemetryStatus: 'Telemetry Status',
    safetyIndex: 'Safety Index',
    headcountActive: 'Headcount Active',
    environmentCore: 'Core Environment',
    surfaceWind: 'Surface Wind',
    powerAllocation: 'Power Allocation',
    mineVentilation: 'Mine Ventilation Flow',
    aquiferFluid: 'Aquifer Fluid Recovery',
    resourceType: 'Resource Type',
    launchTour: 'Launch Tour',
    tourStationDepot: 'ACTIVE TOUR DEPOT',
    camReticulation: 'CAM RETICULATION: ACTIVE',
    projectStations: 'PROJECT STATIONS:',
    prevNode: 'PREV NODE',
    nextNode: 'NEXT NODE',
    selectConcessionPano: 'SELECT CONCESSION PANORAMA',
    howToNavigateTour: 'How to Navigate Tour:',
    howToNavigateTourDesc: 'Use the console selection above to switch concessions. Inside the camera screen, click on pulsate gold "i" indicators to scan geologic arrays, autonomous equipment metrics, and metallurgical separation tanks.',
    complianceWarning: 'Require official site inspections or live physical core auditing visits? Fill out compliance credentials in our Inquiry Terminal for verification.',
    canadianCompliance: 'Compliant with Canadian NI 43-101',

    // Projects Prospectus
    prospectusTitle: 'Consolidated Mineral Reserves',
    prospectusHeader: 'Proven Projects',
    prospectusHeaderPost: ' & Drill Assays',
    prospectusDesc: 'Every project is backed by comprehensive drilling core data, independent Qualified Persons (QP) geological reviews, and capital payback metrics compliant with NI 43-101 protocols.',
    filterAll: 'All Deposits',
    filterGold: 'Gold Projects',
    filterCopper: 'Copper Assets',
    filterLithium: 'Lithium Brine',
    phaseLabel: 'Phase',
    tonnageLabel: 'Estimated Resource/Reserve',
    gradeLabel: 'Resource Grade',
    lifeLabel: 'Estimated Mine Life',
    lifeYears: 'Years',
    capexLabel: 'CapEx Required',
    npvLabel: 'Net Present Value (NPV)',
    irrLabel: 'Post-Tax IRR',
    coordinateLabel: 'Coordinates',
    viewDrillAssays: 'View Core Drill Assays',
    hideDrillAssays: 'Hide Drill Assays',
    drillHoleID: 'Drill Hole ID',
    interceptDepth: 'Intercept Depth',
    interceptGrade: 'Mineral Grade',
    lithologyType: 'Geological Lithology',
    highlightsTitle: 'PROJECT HIGH-LEVEL HIGHLIGHTS',
    securedDocument: 'SECURED DOCUMENT MATRIX',
    requestPreFeas: 'Request Pre-Feasibility Sheet',
    unlockedDoc: 'UNLOCKED CORE REPORT',
    openPdfViewer: 'Open PDF Document Reader',

    // ESG & Safety Dashboard
    esgSubtitle: 'Audited Ecological & Preventive Performance Metrics',
    esgTitle: 'Environmental, ',
    esgTitlePost: 'Social & Carbon Auditing',
    esgDesc: 'MineX prioritizes low-impact extraction technologies, safety, and sustainable gold, silver, and bronze processing. Our real-time ESG ledger records key operational metrics.',
    injuryFreeTitle: 'Injury-Free Milestones',
    injuryFreeDesc: '3.2M cumulative operating hours without single Lost Time Incident (LTI). Industry leading field management.',
    waterRecycleTitle: 'Water Fluid Recovery',
    waterRecycleDesc: 'Aura and Copper Crest recycle 95%+ of metallurgical fluids. Zero discharge into public water basins.',
    cleanEnergyTitle: 'Clean Energy Grid Share',
    cleanEnergyDesc: 'Direct integration with hydroelectric plants and regional solar power grids to charge local EV fleet machinery.',
    esgIndicatorsTitle: 'ANNUAL SYSTEM CARBON METRICS (CY25/CY26)',
    methanePpm: 'Methane Inflow Content',
    flotationRecycleRate: 'Metallurgical Recirculation Rate',
    groundwaterAcre: 'Groundwater Water Balance Impact',
    carbonScope1: 'Scope 1 Heavy Diesel Emissions',
    aquiferSafetyLabel: 'Local Aquifer Hydrology',
    esgVerification: 'MineX is externally audited by Greenstone Assurance Corp. Meets UN Sustainable Development Goals (SDG 6, 7 & 12).',

    // Geology Library
    geoLibraryTitle: 'Sovereign Drilling Assays',
    geoLibrarySubtitle: 'Geological Library',
    geoLibrarySubtitlePost: ' & Core Registers',
    geoLibraryDesc: 'Access historical drilling core registries, structural rock studies, and official feasibility resource models. Secured technical reports require instant verification via Inquiry Terminal.',
    searchLibrary: 'Search Technical Reports or Keywords...',
    allDocuments: 'ALL DEPOSITED REPORTS',
    docType: 'DOCUMENT TYPE',
    docSize: 'DATA SIZE',
    docDate: 'REVISION DATE',
    statusLocked: 'SECURED - GATED FOR Stakeholder Verification',
    statusUnlocked: 'OPEN ACCESS - Download Ready',
    lockedAction: 'Verify Credentials & Access',
    unlockedAction: 'Download PDF Assays',

    // Newsroom
    newsTitle: 'Operational Milestones & Briefings',
    newsHeader: 'MineX ',
    newsHeaderPost: 'Newsroom & Updates',
    newsDesc: 'Track core financial reports, breakthrough drilling intercepts, or major offtake partnerships dispatched directly from corporate headquarters.',
    readPrepText: 'Read full corporate bulletin',
    filterAllNews: 'All Updates',
    bulletinSummary: 'OFFICIAL Bulletins',

    // Inquiry Terminal
    terminalHeader: 'Institutional Portal',
    terminalTitle: 'Inquiry Terminal',
    terminalTitlePost: ' & Access Portal',
    terminalDesc: 'Qualify for private project data rooms, request high-resolution core assay files, or coordinate structured asset briefings with corporate executives.',
    formAum: 'Under Management (AUM)',
    formSmelter: 'Technical Refining capacity',
    formAuthority: 'Department / Agency name',
    formNotes: 'Inquiry Details & Focus Projects',
    formNotesDesc: 'Describe requested technical data, offtake timing, or community scope.',
    audienceLabel: 'IDENTIFY YOUR STAKEHOLDER MATRIX',
    nameLabel: 'Your Official Full Name',
    emailLabel: 'Professional Business Email',
    orgLabel: 'Institution / Corporate Entity',
    projectFocusLabel: 'Indicated Concession Focus',
    selectProjectPlaceholder: '-- Select concession focus --',
    btnVerifyAccess: 'Authorize & Retrieve Secured Geo-Files',
    fileSecurityInfo: 'SECURE CORE: Submitting this form authorizes encrypted retrieval credentials and grants temporal pass tokens to your professional email.',
    verifiedRegistryTitle: 'AUTHENTICATION SUITE RUNNING',
    verifiedRegistrySuccess: 'Secured Data Access Granted! Temporal token holds have been dispatched to',
    accessTargetDoc: 'ACCESS GATED FILE:',
    sovereignMeetingCal: 'Sovereign Briefing Calendar',
    coordinateMeeting: 'Coordinate 1-on-1 Regulatory or Capital Calls',
    selectFocusSlot: 'Select focus slot',
    scheduleBriefing: 'Schedule Briefing Slot',
    briefingSlotHeld: 'Briefing Slot Held',

    // AI Assistant
    aiAssistantTitle: 'MINEX ORE & GEOLOGICAL SUPPORT',
    aiAssistantVersion: 'System Core Version 1.84',
    aiAssistantPlaceholder: 'Ask core assay records or offtake parameters...',
    recommendedLoops: 'RECOMMENDED ANALYTIC LOOPS',
    queryingDb: 'Querying reservoir metrics database...',
    // Stones Tracker
    stonesTab: 'Stones Sold',
    stonesHeaderBadge: 'CUSTOM GEM & MINERAL TRACKER',
    stonesTitle: 'Reserve Stone Registry',
    stonesTitlePost: '& Valuations',
    stonesDesc: 'Inspect the specific shapes, sizes, and annual sales costs of rare crystals, diamonds, and metallurgy assets processed across our high-performing mines.',
    totalRegistryQuantity: 'TOTAL PIECES SOLD',
    totalCapitalReceipts: 'TOTAL SALES VALUE',
    averageUnitAssess: 'AVG UNIT VALUE',
    annualRevenueStreams: 'ANNUAL PRECISION VALUE STREAMS ($ USD)',
    verifiedAudits: 'Audited Data',
    projected: 'Proj',
    reserveSourcingNote: 'Reserve stone sales represent specialty gemstones and custom native mineral structures recovered during development drift blast operations. Revenues directly offset capital expenditure (CapEx) schedules.',
    bulkEstimatorTitle: 'Custom Offtake & Cost Estimator',
    bulkEstimatorDesc: 'Select custom shape characteristics, target grade, cut, and weight to calculate verified bulk contract prices for secure raw mineral lots.',
    calcStoneType: 'Select Mineral Class',
    calcShapeOpt: 'Target Shape Style',
    calcGradeOpt: 'Grade/Clarity Target',
    calcSizeOpt: 'Indicated Stone Size (Per Piece)',
    calcQtyOpt: 'Quantity (Pieces Sold/Ordered)',
    calculateReceipt: 'GENERATE QUOTE STATEMENT',
    filterVault: 'Filter Active Sales Registers',
    searchStonesPlaceholder: 'Search name, grade, site...',
    allYears: 'All Fiscal Years',
    allTypes: 'All Mineral Classes',
    allShapes: 'All Stone Shapes',
    colStoneName: 'Stone / Asset Class',
    colShape: 'Shape Character',
    colSize: 'Individual Size',
    colQtySold: 'Quantity Sold',
    colUnitCost: 'Unit Cost (USD)',
    colTotalCost: 'Annual Cost Stream',
    colYear: 'Fiscal Period',
    colSite: 'Sourced Site',
    noStonesFound: 'No records match target queries.',
  },
  fr: {
    overview: 'Aperçu',
    tradeTab: 'Commerce Global',
    liveMap: 'Carte en Direct & Visites',
    resourceProjects: 'Projets de Ressources',
    esgSafety: 'RSE & Sécurité',
    geologicalLibrary: 'Bibliothèque Géologique',
    investorRelations: 'Relations Investisseurs',
    inquireTerminal: "Terminal d'Information",
    qualifyAccess: "S'ENREGISTRER POUR L'ACCÈS",
    liveIndex: 'Indice des Minéraux en Direct LME/NYMEX:',
    companyTitle: 'MineX Or, Argent & Bronze',
    companySubtitle: 'Opérations Stratégiques d’Or, d’Argent et de Bronze',

    heroTitlePre: 'Échelle autonome.',
    heroTitlePost: 'Souveraineté des ressources.',
    heroSubtitle: 'MineX est un champion des ressources de premier ordre produisant de l\'or, de l\'argent, du bronze, du cuivre de haute pureté et du lithium à faible empreinte de carbone dans l\'OCDE.',
    exploreProjectsButton: 'Explorer le Portefeuille d\'Actifs',
    secureAccessButton: 'Accéder aux Géo-Données Sécurisées',
    activeConcessions: 'Concessions Actives',
    combinedReserves: 'Réserves Combinées',
    esgCarbonSc: 'Bilan Carbone RSE',
    annualTarget: "Objectif Annuel d'Or",
    investorPortal: 'Portail des Investisseurs Institutionnels',
    partnerPortal: 'Offtakeurs & Partenaires Fondeurs',
    governmentPortal: 'Gouvernements & Organes de Régulation',
    verifyRegistry: 'Vérifier le Registre Global des Actifs',
    submitSpecSheets: 'Soumettre les Spécifications Métallurgiques',
    inspectEsgPiles: 'Inspecter les Accréditations Environnementales',

    tierOneCapital: 'Capital Concentré de Premier Ordre',
    tierOneCapitalDesc: 'Nous opérons exclusivement dans des juridictions minières stables, démocratiques et conformes aux protocoles de l’OCDE, garantissant la chaîne d’approvisionnement.',
    tierOneCapitalAction: 'Vérifier les Juridictions',
    lowCarbonPath: 'Faible Bilan Carbone Traçable',
    lowCarbonPathDesc: 'De l’alimentation par réseau solaire à l’électrification complète des parcs d’engins souterrains, nous fournissons des concentrés premium certifiés bas carbone.',
    lowCarbonPathAction: 'Inspecter les Objectifs RSE',
    institutionalScale: 'Échelle Institutionnelle Qualifiée',
    institutionalScaleDesc: 'Nos sites d’exploitation représentent plus de 22,4 millions d’onces d’équivalent-or de réserves prouvées, étayées par des tables d’analyses de carottage en libre accès aux chercheurs.',
    institutionalScaleAction: 'Explorer le Bureau de SÉLECTION',

    operationsTitle: 'Actifs & Télémétries en Direct',
    operationsHeader: 'Carte Interactive',
    operationsHeaderPost: ' & Visites Virtuelles',
    operationsDesc: 'Vérifiez nos activités en temps réel. Examinez nos concessions ou lancez une visite virtuelle 360° de nos galeries, laboratoires d’analyse et chambres d’extraction.',
    tabLiveMap: 'Carte des Opérations',
    tabVirtualTour: 'Visite Virtuelle 360°',
    satCoordinateSys: 'SYSTÈME DE COORDONNÉES PAR SATELLITE',
    liveGpsStream: 'Flux GPS en Direct Actif',
    concessionHub: 'CENTRE DE CONCESSION',
    telemetryStatus: 'État de la Télémétrie',
    safetyIndex: 'Indice de Sécurité',
    headcountActive: 'Effectif Actif',
    environmentCore: 'Environnement de Base',
    surfaceWind: 'Vent de Surface',
    powerAllocation: 'Allocation d\'Énergie',
    mineVentilation: 'Flux de Ventilation Souterrain',
    aquiferFluid: 'Récupération d\'Eau de l\'Aquifère',
    resourceType: 'Type de Ressource',
    launchTour: 'Lancer la Visite',
    tourStationDepot: 'STATION DE VISITE EN ACTIVITÉ',
    camReticulation: 'RÉTICULATION CAMÉRA : ACTIVE',
    projectStations: 'STATIONS DU PROJET :',
    prevNode: 'NŒUD PRÉCÉDENT',
    nextNode: 'NŒUD SUIVANT',
    selectConcessionPano: 'SÉLECTIONNER LE PANORAMA DE LA CONCESSION',
    howToNavigateTour: 'Comment Naviguer dans la Visite :',
    howToNavigateTourDesc: 'Utilisez le sélecteur ci-dessus pour basculer entre les sites. Dans l\'écran vidéo, cliquez sur les icônes dorées pulsantes "i" pour analyser les couches géologiques, les engins autonomes et les cuves de séparation.',
    complianceWarning: 'Vous devez faire une inspection officielle sur place ou auditer les carottages physiques ? Remplissez vos accréditations dans le Terminal d\'Information.',
    canadianCompliance: 'Conforme à la Norme Canadienne NI 43-101',

    prospectusTitle: 'Réserves Minérales Consolidées',
    prospectusHeader: 'Projets Certifiés',
    prospectusHeaderPost: ' & Essais de Forage',
    prospectusDesc: 'Chaque projet s\'appuie sur des données de carottage de forage transparentes, des revues géologiques par des Personnes Qualifiées (QP) indépendantes et des indicateurs de retour sur investissement conformes à la norme canadienne NI 43-101.',
    filterAll: 'Tous les Gisements',
    filterGold: 'Projets d\'Or',
    filterCopper: 'Actifs de Cuivre',
    filterLithium: 'Bassin de Lithium',
    phaseLabel: 'Phase',
    tonnageLabel: 'Réserves et Ressources Estimées',
    gradeLabel: 'Teneur du Gisement',
    lifeLabel: 'Durée de Vie Estimée',
    lifeYears: 'Ans',
    capexLabel: 'CapEx Initial Requis',
    npvLabel: 'Valeur Actuelle Nette (VAN)',
    irrLabel: 'TRI Après Impôt',
    coordinateLabel: 'Coordonnées',
    viewDrillAssays: 'Voir les Essais de Forage',
    hideDrillAssays: 'Masquer les Essais',
    drillHoleID: 'ID du Trou de Forage',
    interceptDepth: 'Profondeur Interceptée',
    interceptGrade: 'Teneur Minérale',
    lithologyType: 'Lithologie Géologique',
    highlightsTitle: 'PRINCIPAUX POINTS CLÉS DU PROJET',
    securedDocument: 'MATRICE DES DOCUMENTS SÉCURISÉS',
    requestPreFeas: 'Demander l\'Étude de Pré-Faisabilité',
    unlockedDoc: 'RAPPORT DE DEGRÉ DE CONFIANCE SÉCURISÉ',
    openPdfViewer: 'Ouvrir le Lecteur de PDF',

    esgSubtitle: 'Métriques d\'Impact Écologique et Performance Préventive Audités',
    esgTitle: 'Performances ',
    esgTitlePost: 'RSE, Environnement & Carbone',
    esgDesc: 'MineX accorde une priorité absolue aux technologies d\'extraction d’or, d’argent et de bronze à faible impact et à la sécurité de ses collaborateurs.',
    injuryFreeTitle: 'Performance Sécurité',
    injuryFreeDesc: 'Plus de 3,2 millions d\'heures de travail combinées sans aucun accident avec arrêt (LTI). Encadrement de pointe.',
    waterRecycleTitle: 'Recyclage des Fluides',
    waterRecycleDesc: 'Nos sites d\'Aura et de Copper Crest recyclent 95%+ des fluides métallurgiques. Aucun rejet dans les bassins publics.',
    cleanEnergyTitle: 'Énergie Propre Intégrée',
    cleanEnergyDesc: 'Connexion directe à des barrages hydroélectriques et à des centrales solaires régionales pour alimenter nos parcs d\'engins électriques.',
    esgIndicatorsTitle: 'BILAN DE CARBONE DU SYSTÈME (CY25/CY26)',
    methanePpm: 'Teneur en Méthane Souterrain',
    flotationRecycleRate: 'Taux de Recirculation Métallurgique',
    groundwaterAcre: 'Impact sur le Bilan de la Nappe Phréatique',
    carbonScope1: 'Émissions Directes Diesel Lourd (Scope 1)',
    aquiferSafetyLabel: 'Hydrologie de l\'Aquifère Local',
    esgVerification: 'MineX fait l\'objet d\'audits externes indépendants par Greenstone Assurance Corp. Conforme aux Objectifs de Développement Durable (ODD ODD 6, 7 & 12).',

    geoLibraryTitle: 'Sondages d\'Assay Souverains',
    geoLibrarySubtitle: 'Bibliothèque',
    geoLibrarySubtitlePost: ' Géologique & Carottages',
    geoLibraryDesc: 'Accédez aux archives de forage historiques, aux études pétrographiques et aux dossiers de faisabilité des ressources. La consultation des rapports techniques nécessite un jeton d\'accès instantané.',
    searchLibrary: 'Rechercher des rapports techniques ou mots-clés...',
    allDocuments: 'TOUS LES RAPPORTS DÉPOSÉS',
    docType: 'TYPE DE RAPPORT',
    docSize: 'TAILLE DES DONNÉES',
    docDate: 'DATE DE RÉVISION',
    statusLocked: 'SÉCURISÉ - Nécessite une Vérification d\'Accréditation',
    statusUnlocked: 'ACCÈS LIBRE - Téléchargement Prêt',
    lockedAction: 'Vérifier mes Informations & Accéder',
    unlockedAction: 'Télécharger les Essais de Forage',

    newsTitle: 'Jalons Opérationnels & Communiqués',
    newsHeader: 'Actualités ',
    newsHeaderPost: ' & Rapports Financiers',
    newsDesc: 'Suivez les derniers résultats de forage, les indicateurs trimestriels consolidés ou les partenariats stratégiques d\'approvisionnement.',
    readPrepText: 'Consulter le communiqué officiel',
    filterAllNews: 'Toutes les Actualités',
    bulletinSummary: 'Bulletins Officiels',

    terminalHeader: 'Portail des Partenaires',
    terminalTitle: 'Terminal',
    terminalTitlePost: " d'Information & d'Accès",
    terminalDesc: 'Accédez de manière sécurisée aux bases de données géologiques, demandez des études de carottage avancées ou calez des réunions stratégiques avec nos directeurs.',
    formAum: 'Actifs sous Gestion (AUM)',
    formSmelter: 'Capacité Technique d\'Affinage',
    formAuthority: 'Nom de l\'Organisme / Ministère',
    formNotes: 'Informations Complémentaires & Projets Ciblés',
    formNotesDesc: 'Décrivez vos besoins en données techniques, d\'offtake ou environnementaux.',
    audienceLabel: 'SÉLECTIONNEZ VOTRE MATRICE DE PARTENARIAT',
    nameLabel: 'Votre Nom Complet Officiel',
    emailLabel: 'Adresse E-mail Professionnelle',
    orgLabel: 'Institution / Entité Corporative',
    projectFocusLabel: 'Projet de Concession Visé',
    selectProjectPlaceholder: '-- Sélectionnez une concession --',
    btnVerifyAccess: 'S\'Authentifier & Accéder aux Fichiers Géologiques',
    fileSecurityInfo: 'COCKPIT SÉCURISÉ : Soumettre le formulaire transmet instantanément vos droits et génère des jetons d\'accès sécurisés envoyés à votre adresse professionnelle.',
    verifiedRegistryTitle: 'AUTHENTIFICATION EN COURS D\'EXÉCUTION',
    verifiedRegistrySuccess: 'Accès sécurisé accordé ! Les jetons temporaires et de chiffrement ont été expédiés à',
    accessTargetDoc: 'TÉLÉCHARGEMENT COMPLIEMENTAIRE SÉCURISÉ :',
    sovereignMeetingCal: 'Calendrier de Réunion des Directeurs',
    coordinateMeeting: 'Planifier un Appel Réglementaire ou d\'Investissement 1-on-1',
    selectFocusSlot: 'Sélectionner le créneau d\'attention',
    scheduleBriefing: 'Réserver le Créneau de Briefing',
    briefingSlotHeld: 'Créneau Réservé avec Succès',

    aiAssistantTitle: 'SUPPORT GÉOLOGIQUE MINEX',
    aiAssistantVersion: 'Version du Noyau Système 1.84',
    aiAssistantPlaceholder: 'Demandez nos métriques de réserve ou d\'offtake...',
    recommendedLoops: 'RECOMMANDATIONS D\'EXPLORATION',
    queryingDb: 'Interrogation de la base géothermique...',
    // Stones Tracker
    stonesTab: 'Pierres Vendues',
    stonesHeaderBadge: 'REGISTRE DES MINÉRAUX ET PIERRES PRÉCIEUSES',
    stonesTitle: 'Registre des Pierres',
    stonesTitlePost: '& Estimations',
    stonesDesc: 'Consultez les formes, les dimensions et les coûts de vente annuels spécifiques des cristaux rares, diamants et anodes de cuivre raffinés sur nos sites d’exploitation.',
    totalRegistryQuantity: 'TOTAL DES UNITÉS VENDUES',
    totalCapitalReceipts: 'VALEUR TOTALE DES VENTES',
    averageUnitAssess: 'VALEUR UNITAIRE MOYENNE',
    annualRevenueStreams: 'FLUX DE REVENUS ANNUELS DE PRÉCISION ($ USD)',
    verifiedAudits: 'Données Auditées',
    projected: 'Proj',
    reserveSourcingNote: 'Les ventes de pierres de réserve représentent les gemmes particulières récupérées lors du percement des galeries. Ces revenus compensent directement les dépenses de CapEx.',
    bulkEstimatorTitle: 'Estimateur de Contrat et de Volumes',
    bulkEstimatorDesc: 'Sélectionnez la forme, la pureté et le poids pour calculer des estimations tarifaires de lots bruts sous contrats sécurisés.',
    calcStoneType: 'Sélectionner la classe minérale',
    calcShapeOpt: 'Forme de Coupe Ciblée',
    calcGradeOpt: 'Niveau de Pureté / Clarté',
    calcSizeOpt: 'Taille Individuelle de Gemme',
    calcQtyOpt: 'Quantité (Nombre d’Unités)',
    calculateReceipt: 'GÉNÉRER UN DEVIS DE CONTRAT',
    filterVault: 'Filtrer le Registre des Ventes',
    searchStonesPlaceholder: 'Rechercher nom, pureté, site...',
    allYears: 'Toutes les années fiscales',
    allTypes: 'Toutes les classes minérales',
    allShapes: 'Toutes les formes de pierre',
    colStoneName: 'Type de Pierre / Catégorie',
    colShape: 'Forme & Coupe',
    colSize: 'Dimension Initiale',
    colQtySold: 'Unités Vendues',
    colUnitCost: 'Coût Unitaire (USD)',
    colTotalCost: 'Revenu de Vente Annuel',
    colYear: 'Période Fiscale',
    colSite: 'Site d’Origine',
    noStonesFound: 'Aucun enregistrement ne correspond aux critères filtrés.',
  },
  rw: {
    overview: 'Incamake',
    tradeTab: 'Gucuruza Amabuye',
    liveMap: 'Ikarita n\'Ibihamya',
    resourceProjects: 'Imishinga y’Amabuye',
    esgSafety: 'Umutekano n’Ibidukikije (RSE/ESG)',
    geologicalLibrary: 'Ububiko bw’Ubutaka',
    investorRelations: 'Amakuru & Abashoramari',
    inquireTerminal: 'Ibiro Bikuru Byo Gusaba Amakuru',
    qualifyAccess: 'SABA UBURENGANZIRA BWO KWINJIRA',
    liveIndex: 'Ibiciro by’Amabuye Live LME/NYMEX:',
    companyTitle: 'MineX Gold, Silver & Bronze',
    companySubtitle: 'Zahabu, Ifeza (Silver) & Bronze Ibirombe Kamere',

    heroTitlePre: 'Gucukura bigezweho.',
    heroTitlePost: 'Iterambere ryizewe.',
    heroSubtitle: 'MineX ni icyitegererezo mu gucukura zahabu nziza, ifeza, bronze, imirunga y’umuringa itunganijwe, hamwe n’amabuye ya lityumu akurwa mu butaka mu buryo bwo kubungabunga ibidukikije.',
    exploreProjectsButton: 'Reba Imishinga n’Ibucukurwa',
    secureAccessButton: 'Injira mu Bubiko Bucometse',
    activeConcessions: 'Imirasire y’Ubucukuzi',
    combinedReserves: 'Amabuye Twizigiye',
    esgCarbonSc: 'Ingufu n’Ibidukikije',
    annualTarget: 'Intego ya Zahabu ku Mwaka',
    investorPortal: 'Abanyamigabane n’Ikigega cy’Imari',
    partnerPortal: 'Inganda n’Aruganda Rutunganya Shabaha',
    governmentPortal: 'Leta n’Inzego Zigenzura Ibidukikije',
    verifyRegistry: 'Genya Ububiko bw’Amabuye ku Isi',
    submitSpecSheets: 'Tanga Imiterere y’Ubutare n’Ubutaka',
    inspectEsgPiles: 'Genya Impapuro z’Ibyangombwa by’Ibidukikije',

    tierOneCapital: 'Icyerekezo ku bihugu Bitekanye',
    tierOneCapitalDesc: 'Ibikorwa byacu byose bikorerwa mu bihugu bitajegajega, byubahiriza amategeko n’amahame avuguruye ya OECD, ibyo bikizeza abaguzi umutekano ku bicuruzwa bicyurwa.',
    tierOneCapitalAction: 'Genya Umutekano w’Ibihugu',
    lowCarbonPath: 'Kubungabunga Ibidukikije mu Mihigo',
    lowCarbonPathDesc: 'Kuva ku rurere rw’ingufu z’imirasire y’izuba kugeza ku mashine zikoresha amashanyarazi mu nsi y’ubutaka, twubahiriza kubungabunga ibidukikije no kugabanya imyotsi y’inganda.',
    lowCarbonPathAction: 'Reba Intego z’Ibidukikije',
    institutionalScale: 'Amabuye y’Agaciro ku Rugero Rufatika',
    institutionalScaleDesc: 'Ubutaka n’imishinga yacu bifite ubushobozi bwa miriyoni 22.4 z’unsi (oz) z’amabuye y’agaciro ya zahabu na shabaha, bishimangirwa n’inyandiko n’isuzuma rusange by’inzobere bishyizwe mu ruhame.',
    institutionalScaleAction: 'Shakashaka mu Bubiko bw’Amacuruzwa',

    operationsTitle: 'Amakuru y’Ibirombe mu Gihe Nyacyo',
    operationsHeader: 'Interactive Map',
    operationsHeaderPost: ' & Gusura Ibirombe',
    operationsDesc: 'Koresha ikarita yacu urebe uko imishinga ihagaze muri iki gihe. Ushobora no gusura aho ducukurira hashyizwe mu buryo bwa 365° unyuze kuri interineti.',
    tabLiveMap: 'Ikarita Operational Live',
    tabVirtualTour: 'Gusura Ibirombe muri 3D (360°)',
    satCoordinateSys: 'STELLITE GPS COORDINATE NETWORKS',
    liveGpsStream: 'Ihuza rya GPS rirahagaze neza',
    concessionHub: 'IBIROMBE BYACU',
    telemetryStatus: 'Uko Ibyuma Bihagaze',
    safetyIndex: 'Gukumira Impanuka',
    headcountActive: 'Abakozi Bahari',
    environmentCore: 'Ubukana n’Ibyoroshye mu Kirombe',
    surfaceWind: 'Umuyaga wo Hanze',
    powerAllocation: 'Inkomoko y\'Ingufu',
    mineVentilation: 'Urujya n\'Uruzaza rw\'Umwuka',
    aquiferFluid: 'Kuyungurura Amazi y\'Ubutaka',
    resourceType: 'Ubwoko bw\'Amabuye',
    launchTour: 'Sura Imbere mu Kirombe',
    tourStationDepot: 'AHO URI GUSURA MU KIROMBE',
    camReticulation: 'KAMERA ZO MU KIROMBE: ZIRAKORA',
    projectStations: 'AMAHURIRO Y\'URUGENDO:',
    prevNode: 'INYUMA',
    nextNode: 'IMBERE',
    selectConcessionPano: 'HITAMO IKIROMBE CG ICUCUKURIDRO',
    howToNavigateTour: 'Uko Wabona Amakuru mu Rugendo:',
    howToNavigateTourDesc: 'Koresha aka kabaturo kari hejuru uhitemo ikirombe ushaka gusura. Kanda ku kimenyetso cy\'umuhondo cyanditseho "i" kugira ngo urebe imitunganirize y\'amabuye n\'imikorere y\'imashini.',
    complianceWarning: 'Waba ushaka gusura ibirombe byacu imbere cyangwa gusuzuma ubutaka dushyiraho amabuye? Cyura impapuro z’uburenganzira muri inquiry terminal.',
    canadianCompliance: 'Rirubahiriza NI 43-101 rya Kanada',

    prospectusTitle: 'Igereranywa Ry\'Amabuye Yose Hamwe',
    prospectusHeader: 'Imishinga ',
    prospectusHeaderPost: ' n\'Isesengurwa ry\'Ubutaka',
    prospectusDesc: 'Buri mushinga ugaragarizwaho amakuru ahamye y’ibipimo by’ubutaka, ibyemezo by’inzobere (QP) zitemera kubogama, n’amasezerano arengera abashoramari cyane cyane yubahiriza amategeko ya NI 43-101.',
    filterAll: 'Amabuye Yose',
    filterGold: 'Zahabu Gusa',
    filterCopper: 'Umuringa (Copper)',
    filterLithium: 'Amabuye ya Lityumu',
    phaseLabel: 'Icyiciro Umushinga Ugezemo',
    tonnageLabel: 'Ingano y’Amabuye Ahari',
    gradeLabel: 'Ubuziranenge bw’Ubutare',
    lifeLabel: 'Imyaka Ikirombe Kimara Gikora',
    lifeYears: 'Imyaka',
    capexLabel: 'Amafaranga yo Guhitamo Umushinga',
    npvLabel: 'Agaciro k’Imari Muri iki Gihe (NPV)',
    irrLabel: 'Inyungu Ikurwamo (IRR)',
    coordinateLabel: 'Aho Biherereye kuri GPS',
    viewDrillAssays: 'Reba Ibipimo by\'Ubutaka (Drill)',
    hideDrillAssays: 'Bika Ibi bipimo',
    drillHoleID: 'Inomero y\'Umwobo w\'Igerageza',
    interceptDepth: 'Ubujyakuzimu bw\'Igerageza',
    interceptGrade: 'Ubuziranenge ku gipimo cy\'Ubutare',
    lithologyType: 'Ubwoko bw\'Ibuye mu Butaka',
    highlightsTitle: 'IBY’INGENZI KURI UYU MUSHINGA',
    securedDocument: 'UBUBIKO BW’INYANDIKO SEKURIZE',
    requestPreFeas: 'Saba Doc y’Isesengura ry’Imari',
    unlockedDoc: 'DOCUMENT YAFUNGUWE IMBERE',
    openPdfViewer: 'Gufungura no Gusoma Inyandiko (PDF)',

    esgSubtitle: 'Ibipimo bishimangira Kubungabunga Ibidukikije n’Umutekano ku Abakozi',
    esgTitle: 'Mihigo y’Ibidukikije, ',
    esgTitlePost: 'Imibereho y’Abaturage n’Iterambere',
    esgDesc: 'MineX ishyira imbere uburyo bwo gukoresha ingufu n’amazi bitangiza ibidukikije hamwe n’umutekano uzira amakemwa mu gucukura zahabu, silver na bronze.',
    injuryFreeTitle: 'Umutekano ku Bakozi',
    injuryFreeDesc: 'Twasoje amasaha arenga miliyoni 3.2 z’akazi mu gihe cy’amezi 6 nta mukozi n’umwe wagize impanuka (LTI-Free). Icunga ryiza ry’umutekano.',
    waterRecycleTitle: 'Koresha Amazi neza',
    waterRecycleDesc: 'Ingamba z’ibicuruzwa by’amazi muri Aura na Copper Crest, 95% y’amazi asubizwa mu ruganda no kuyungururwa ngo adakwirakwira hanze.',
    cleanEnergyTitle: 'Koresha Ingufu Zisanzwe',
    cleanEnergyDesc: 'Ihuza ry’ingufu zituruka ku ruzinduko rw’amazi (Hydro) n’imirasire y’izuba mu kuzuza imashini n’imodoka z’amashanyarazi zo mu nsi y’ubutaka.',
    esgIndicatorsTitle: 'IBIPIMO BY’IKOTI NO KUGABANYA IMYOTSI (CY25/CY26)',
    methanePpm: 'Igipimo cy’Umwuka wa Methane',
    flotationRecycleRate: 'Igipimo cyo Gusubiramo Amazi',
    groundwaterAcre: 'Ingaruka ku Mazi y’Ubutaka',
    carbonScope1: 'Imyotsi ya Diesel ku Mashine Monstre',
    aquiferSafetyLabel: 'Umutekano w’Amazi yo mu Butaka',
    esgVerification: 'MineX ikorana n’inzobere mu gupima RSE/ESG rihereye muri Greenstone Assurance Corp. Twubahiriza amasezerano ya UN SDGs 6, 7 & 12.',

    geoLibraryTitle: 'Ibipimo by’Isesengura ry’Amabuye',
    geoLibrarySubtitle: 'Ububiko bwa Siyansi ',
    geoLibrarySubtitlePost: 'y’Ubutaka n’Ubutare',
    geoLibraryDesc: 'Injira mu bushakashatsi bw’ibidukikije, amabuye y’agaciro, ndetse n’ibyegeranyo bijyanye n’isoko. Kugira ngo urangize kwinjira, cyura impapuro n’imyirondoro yawe mu Inquiry Terminal kuko inyandiko zimwe zifunze.',
    searchLibrary: 'Shakisha inyandiko n’amakuru ashakishwa...',
    allDocuments: 'IBYEGERANYO N’INYANDIKO ZOSE',
    docType: 'UBWOKO BW’INYANDIKO',
    docSize: 'INGANO YISE',
    docDate: 'UMWAKO CG IDATE BYAVUGURUWE',
    statusLocked: 'BIFUNZE - Bizasuzumwa unyuze muri Inquiry Terminal',
    statusUnlocked: 'BIFRE - Ushobora kubisoma cg kubipakurura',
    lockedAction: 'Saba Gufungurirwa unyuze aha',
    unlockedAction: 'Pakurura Inyandiko (PDF/Assays)',

    newsTitle: 'Amakuru Mashya n’Itangazamakuru',
    newsHeader: 'Amakuru ya ',
    newsHeaderPost: 'MineX Mining ku Mwaka',
    newsDesc: 'Bona amakuru ajyanye n’inyungu ku executes, isuzumwa ry’ibipimo by’ubutaka, cyangwa amasezerano akomeye n’inganda ku Isi dutangariza mu biro bikuru.',
    readPrepText: 'Soma inyandiko yose y’iri tangazo',
    filterAllNews: 'Amakuru Yose',
    bulletinSummary: 'AMATANGAZO Y’IBIRO BIKURU',

    terminalHeader: 'Inquiry & Kubaza',
    terminalTitle: 'Ibiro Bikuru By’Inquiry',
    terminalTitlePost: ' n’Ishakiro Ry’Uburenganzira',
    terminalDesc: 'Saba uburenganzira bwo gusoma inyandiko zigezweho zo mu birombe byacu, bona inyandiko z’isoko cyangwa usabe kugirana inama n’abayobozi b’ikigo cyacu.',
    formAum: 'Igishoro cy’Ikigo (AUM)',
    formSmelter: 'Ubushobozi bwa Tekiniki bwo gufunda',
    formAuthority: 'Izina rya Minisiteri CG Ikigo cya Leta l',
    formNotes: 'Ibisobanuro Bikubiye mu Kibazo n’Imishinga Umozeho',
    formNotesDesc: 'Sobanura neza amakuru cyangwa inyandiko ushaka, gucuruza cg andi masano dufitanye.',
    audienceLabel: 'HITAMO URUHANDE URIBO MURI IYI MISHINGA',
    nameLabel: 'Amazina Yawe Yose',
    emailLabel: 'Iserifu/Email y’Akazi',
    orgLabel: 'Ikigo cg Umuryango Ukorera',
    projectFocusLabel: 'Indangantego ku Kirombe na Concession',
    selectProjectPlaceholder: '-- Hitamo umushinga uzeho --',
    btnVerifyAccess: 'Saba Uburenganzira bwo kureba impapuro',
    fileSecurityInfo: 'SECURE CORE: Gutsinda iri tumanaho bizaguha uburenganzira bwo kohererezwa ifunguzo zo kwinjira n’impapuro ziboneka muri email yawe.',
    verifiedRegistryTitle: 'ISUZUMA RY’IMYONDORO RIRAKORA...',
    verifiedRegistrySuccess: 'Wahawe Uburenganzira! Imfunguzo z’inzibacyuho zoherejwe kuri email yawe:',
    accessTargetDoc: 'INYANDIKO WASABYE IGENSWA:',
    sovereignMeetingCal: 'Agenda yo Guhura N\'abayobozi',
    coordinateMeeting: 'Saba kuryisanga mu nama ya 1-on-1 n’Abayobozi Bacu',
    selectFocusSlot: 'Hitamo icyiciro cy’isuzuma ushaka',
    scheduleBriefing: 'Tegeka Isaha y’Inama',
    briefingSlotHeld: 'Isaha n’umunsi byafatiwe neza mu buryo bwizewe',

    aiAssistantTitle: 'MINEX ORE AI SUPPORT',
    aiAssistantVersion: 'Core Version 1.84',
    aiAssistantPlaceholder: 'Baza amakuru y’amabuye, ingufu cg isoko rya zahabu...',
    recommendedLoops: 'IBYANGO RYIZA BYO KUBYUTSA AMASHAKISHO',
    queryingDb: 'Gushakisha mu bubiko bw’ubutare n’amabuye...',
    // Stones Tracker
    stonesTab: "Amabuye Yaguzwe",
    stonesHeaderBadge: "IGEPURURWA RY'AMABUYE N'UBUTARE KURI LIVE",
    stonesTitle: "Urugereko rw'Amabuye",
    stonesTitlePost: "n'Ibiciro",
    stonesDesc: "Soma usesengure imiterere, ibipimo n'ibiciro ku mwaka by'amabuye y'agaciro y'indobanure na zahabu bikurwa mu birombe bya MineX.",
    totalRegistryQuantity: 'INGANO YOSE YAGURISHIJWE',
    totalCapitalReceipts: 'AGACIRO KOSE HAMWE YAGURISHIJWE',
    averageUnitAssess: 'AGACIRO GAHAGUYE KURI BURI BUCURUZWA',
    annualRevenueStreams: 'IBYIGERANYO BY’INYUNGU KU MWAKA ($ USD)',
    verifiedAudits: 'Amakuru Yemejwe',
    projected: 'Igereranywa',
    reserveSourcingNote: 'Amabuye y’agaciro n’umurunga bishingirwa ku bucukuzi bugezweho bukemura ibibazo by’ingufu n’ubutaka. Inyungu ikurwamo ihita yunganira ingengo y’imari ya CapEx.',
    bulkEstimatorTitle: 'Kugereranya Ingano n\'Ibiciro by\'Amabuye',
    bulkEstimatorDesc: 'Hitamo ireme ry’ibuye, imiterere, n’uburemere kugira ngo uhiteubona inyandiko y’ibiciro ku masoko mpuzamahanga.',
    calcStoneType: 'Hitamo Ubwoko bw’Ibuye',
    calcShapeOpt: 'Hitamo Imiterere Inogeye',
    calcGradeOpt: 'Iremeritse ry’Ibuye (Grade)',
    calcSizeOpt: 'Uburemere cyangwa Uburebure (Piece)',
    calcQtyOpt: 'Inomero y’Amabuye Ushaka',
    calculateReceipt: 'GUKORA INYANDIKO Y\'IBICIRO (QUOTE)',
    filterVault: 'Flitira Inyandiko z\'Ibiciro',
    searchStonesPlaceholder: 'Shakisha izina, ireme, cyangwa ikrombe...',
    allYears: 'Imyaka Yose y’Imari',
    allTypes: 'Ubwoko Bose bw’Ubutare',
    allShapes: 'Imiterere Yose y’Amabuye',
    colStoneName: 'Ubwoko bw’Ibuye',
    colShape: 'Iterambere ry’Ibuye (Shape)',
    colSize: 'Uburemere (Size)',
    colQtySold: 'Ingano Yagurishijwe',
    colUnitCost: 'Igiciro kuri Piece (USD)',
    colTotalCost: 'Inyungu Yose ku Mwaka',
    colYear: 'Igihe cy’Imari',
    colSite: 'Ikirombe Ryaturutsemo',
    noStonesFound: 'Nta makuru ahuye n’ibyo ushaka.',
  },
  es: {
    overview: 'Resumen',
    tradeTab: 'Comercio Global',
    liveMap: 'Mapa en Vivo',
    resourceProjects: 'Proyectos',
    esgSafety: 'RSC y Seguridad',
    geologicalLibrary: 'Biblioteca',
    investorRelations: 'Inversores',
    inquireTerminal: 'Consultas',
    qualifyAccess: 'REQUISITO DE ACCESO',
    liveIndex: 'Índice de Minerales LME/NYMEX:',
    companyTitle: 'MineX Oro, Plata y Bronce',
    companySubtitle: 'Operaciones Estratégicas',
    stonesTab: 'Piedras Vendidas',
    aiAssistantTitle: 'SOPORTE MINEX',
    heroTitlePre: 'Escala autónoma.',
    heroTitlePost: 'Suministro soberano.',
    heroSubtitle: 'MineX es un campeón de recursos de primer nivel que produce oro, plata, bronce, cobre refinado y litio limpio.',
    exploreProjectsButton: 'Explorar Portafolio',
    secureAccessButton: 'Acceso Seguro',
    activeConcessions: 'Concesiones Activas',
    combinedReserves: 'Reservas Combinadas',
    esgCarbonSc: 'Puntuación de Carbono RSC',
    annualTarget: 'Objetivo Anual de Oro',
    investorPortal: 'Portal de Inversores',
    partnerPortal: 'Socios Comerciales',
    governmentPortal: 'Gobiernos Soberanos',
    verifyRegistry: 'Verificar Registro de Activos',
    submitSpecSheets: 'Presentar Hojas Técnicas',
    inspectEsgPiles: 'Inspeccionar Acreditación ESG',
    operationsTitle: 'Activos en Tiempo Real',
    operationsHeader: 'Mapa Interactivo',
    operationsHeaderPost: ' y Visitas',
    operationsDesc: 'Verifique las actividades mineras globales. Explore concesiones activas o inicie recorridos virtuales de 360°.',
    tabLiveMap: 'Mapa Operaciones en Vivo',
    tabVirtualTour: 'Recorrido Virtual 360°',
    satCoordinateSys: 'SATELLITE POSITION COORDINATE SYSTEM',
    liveGpsStream: 'Transmisión GPS Activa',
    concessionHub: 'CENTRO CONCESIÓN',
    telemetryStatus: 'Estado de Telemetría',
    safetyIndex: 'Índice de Seguridad',
    headcountActive: 'Personal Activo',
    environmentCore: 'Ambiente Central',
    surfaceWind: 'Viento en Superficie',
    powerAllocation: 'Asignación de Energía',
    mineVentilation: 'Ventilación de Mina',
    aquiferFluid: 'Recuperación de Acuíferos',
    resourceType: 'Tipo de Recurso',
    launchTour: 'Iniciar Visita',
    tourStationDepot: 'DEPÓSITO DE VISITA ACTIVO',
    camReticulation: 'RETICULACIÓN DE CÁMARA: ACTIVA',
    projectStations: 'ESTACIONES DEL PROYECTO:',
    prevNode: 'NODO ANTERIOR',
    nextNode: 'NODO SIGUIENTE',
    selectConcessionPano: 'SELECCIONAR PANORAMA DE CONCESIÓN',
    howToNavigateTour: 'Cómo navegar por el recorrido:',
    howToNavigateTourDesc: 'Utilice la consola de selección para cambiar de concesión. Haga clic en los indicadores amarillos para ver datos.',
    complianceWarning: '¿Requiere inspecciones oficiales? Complete el formulario de consulta.',
    canadianCompliance: 'Cumple con Canadian NI 43-101',
    geoLibraryTitle: 'Análisis de Perforación',
    geoLibrarySubtitle: 'Biblioteca',
    geoLibrarySubtitlePost: ' y Registros',
    geoLibraryDesc: 'Acceso a registros históricos de perforación y modelos de recursos. Requiere validación.',
    searchLibrary: 'Buscar informes o palabras clave...',
    statusLocked: 'ASEGURADO - REQUIERE VERIFICACIÓN',
    statusUnlocked: 'ACCESO ABIERTO - Listo para descarga',
    lockedAction: 'Verificar Credenciales',
    unlockedAction: 'Descargar PDF Assays',
    newsTitle: 'Hitos Operativos y Boletines',
    newsHeader: 'Noticias de ',
    newsHeaderPost: 'MineX',
    newsDesc: 'Siga los informes financieros clave y descubrimientos de perforación directamente desde la sede.',
    readPrepText: 'Leer boletín corporativo completo',
    filterAllNews: 'Todas las actualizaciones',
    bulletinSummary: 'Boletines Oficiales',
    terminalHeader: 'Portal Institucional',
    terminalTitle: 'Terminal de Consultas',
    terminalTitlePost: ' y Portal de Acceso',
    terminalDesc: 'Califique para salas de datos privadas o coordine sesiones técnicas directas con ejecutivos.',
    formAum: 'Bajo Gestión (AUM)',
    formSmelter: 'Capacidad de Refinación',
    formAuthority: 'Unidad o Agencia Reguladora',
    formNotes: 'Detalles de Consulta y Enfoque',
    formNotesDesc: 'Describa datos técnicos solicitados o la escala del proyecto.',
    audienceLabel: 'IDENTIFIQUE SU MATRIZ DE PARTICIPANTE',
    nameLabel: 'Nombre Completo Oficial',
    emailLabel: 'Correo Electrónico Corporativo',
    orgLabel: 'Institución / Entidad Corporativa',
    projectFocusLabel: 'Enfoque de Concesión Indicado',
    selectProjectPlaceholder: '-- Seleccionar concesión --',
    btnVerifyAccess: 'Autorizar y Obtener Datos Geológicos Eléctricos',
    fileSecurityInfo: 'NÚCLEO SEGURO: Al enviar autoriza la obtención de credenciales seguras enviadas a su correo.',
    verifiedRegistryTitle: 'SISTEMA DE AUTENTICACIÓN EN CURSO',
    verifiedRegistrySuccess: '¡Acceso a Datos Asegurados Concedido! Se ha enviado el token temporal a',
    accessTargetDoc: 'ARCHIVO RESTRINGIDO:',
    sovereignMeetingCal: 'Calendario de Reunión Soberana',
    coordinateMeeting: 'Coordinar Llamadas de Regulación o Capital',
    selectFocusSlot: 'Seleccionar slot',
    scheduleBriefing: 'Programar Sesión de Consulta',
    briefingSlotHeld: 'Ranura Reservada Correctamente',
  },
  zh: {
    overview: '概览',
    tradeTab: '全球贸易',
    liveMap: '实时地图',
    resourceProjects: '资源项目',
    esgSafety: 'ESG与安全',
    geologicalLibrary: '地质文献',
    investorRelations: '投资者关系',
    inquireTerminal: '查询终端',
    qualifyAccess: '资质访问验证',
    liveIndex: 'LME/NYMEX 实时金属指数:',
    companyTitle: 'MineX 金银铜矿业',
    companySubtitle: '战略性金银铜开采业务',
    stonesTab: '已售矿石',
    aiAssistantTitle: 'MINEX 智能支持',
    heroTitlePre: '全自动生产规模。',
    heroTitlePost: '主权资源保障。',
    heroSubtitle: 'MineX 是世界一流的资源领军企业，在多元化的稳定辖区内高效开采高纯度金、银、铜、锂等战略物资。',
    exploreProjectsButton: '浏览资产组合',
    secureAccessButton: '安全地质数据访问',
    activeConcessions: '活动矿区',
    combinedReserves: '总含金储量',
    esgCarbonSc: 'ESG 碳排放评分',
    annualTarget: '年度黄金目标',
    investorPortal: '机构投资者门户',
    partnerPortal: '承购与冶炼合作伙伴',
    governmentPortal: '主权政府和环境保护组',
    verifyRegistry: '验证全球资产名录',
    submitSpecSheets: '提交冶炼技术指标',
    inspectEsgPiles: '审查环境合规资质',
    operationsTitle: '实时全球资产與遥测',
    operationsHeader: '三维地图及探矿',
    operationsHeaderPost: '系统',
    operationsDesc: '监视地表与井下作业。启动360°虚拟漫游，深入钻柱、配料库与浮选分离车间。',
    tabLiveMap: ' live 运营卫星图',
    tabVirtualTour: '360° 实时视频点位',
    satCoordinateSys: '卫星三维空间定位体系',
    liveGpsStream: '实时 GPS 全息数据激活',
    concessionHub: '矿区中心',
    telemetryStatus: '遥测状态',
    safetyIndex: '安全合规系数',
    headcountActive: '在岗操作员工',
    environmentCore: '核心环保指标',
    surfaceWind: '地表风速',
    powerAllocation: '电力负荷分配',
    mineVentilation: '主扇通风流量',
    aquiferFluid: '含水层回收效率',
    resourceType: '主要采掘矿种',
    launchTour: '进入实景漫游',
    tourStationDepot: '互动视频工作栈',
    camReticulation: '探头网卡：正常运转',
    projectStations: '工程探测站点:',
    prevNode: '前一工程点',
    nextNode: '后一工程点',
    selectConcessionPano: '选择矿区透视图',
    howToNavigateTour: '如何进行全息漫游:',
    howToNavigateTourDesc: '可在控制区自由切换点位。在画面中点击闪烁的黄色按钮，调取其遥控机械及工程深度资料。',
    complianceWarning: '需要安排实地现场勘查或核心岩心审计？请填写下方查询表以便尽调审核。',
    canadianCompliance: '符合加拿大 NI 43-101 质量标准',
    geoLibraryTitle: '主权钻探成果与岩样鉴定',
    geoLibrarySubtitle: '地质文献馆',
    geoLibrarySubtitlePost: '及钻探台账',
    geoLibraryDesc: '获取所有开发项目的工程地质报告、详勘资源模型以及环境测评。下载需在终端输入验证码。',
    searchLibrary: '搜索工程报告、钻孔编号或关键字...',
    statusLocked: '已加密 - 需机构客户专区验证',
    statusUnlocked: '开放获取 - 随时可下载',
    lockedAction: '核验资质并读取',
    unlockedAction: '下载 PDF 技术报表',
    newsTitle: '企业重大资讯及运营简报',
    newsHeader: 'MineX ',
    newsHeaderPost: '新闻发布室',
    newsDesc: '追踪由MineX集团温哥华总部发出的实时钻采高品位、生产配额。',
    readPrepText: '核对官方通告全文',
    filterAllNews: '所有新闻汇总',
    bulletinSummary: '官方公告',
    terminalHeader: '投资及承购综合门户',
    terminalTitle: '信息咨询终端',
    terminalTitlePost: '及授权门户',
    terminalDesc: '进行尽职调查资格预审、获取超高分辨率钻孔图像、或与高级合伙人安排专项会谈。',
    formAum: '管理资本规模 (AUM)',
    formSmelter: '冶炼精炼产能 (年)',
    formAuthority: '主管部委或中介机构',
    formNotes: '咨询事项详情及涉及的项目范围',
    formNotesDesc: '请具体陈述所需数据、合资设想或承购吨位。',
    audienceLabel: '标明您的相关利益相关方属性',
    nameLabel: '法定联络人全称',
    emailLabel: '企业官方电子邮箱',
    orgLabel: '投资机构或企业实体英文名',
    projectFocusLabel: '指定的特许权重点',
    selectProjectPlaceholder: '-- 请选择关注的项目 --',
    btnVerifyAccess: '提交审核并获取地质秘钥',
    fileSecurityInfo: '信息防护：您的提交数据将在SSL高强度加密通道中处理，并为对应邮箱分发单次有效的访问信标。',
    verifiedRegistryTitle: '身份认证系统校验中',
    verifiedRegistrySuccess: '高安全级别数据下载资格已确立！安全存取密钥已投递至：',
    accessTargetDoc: '受控档案下载：',
    sovereignMeetingCal: '首脑会晤日程表',
    coordinateMeeting: '协调一对一行业政策或出资细则对话',
    selectFocusSlot: '挑选预约时间段',
    scheduleBriefing: '确立咨询时间窗',
    briefingSlotHeld: '专属会商时段已留存',
  },
  de: {
    overview: 'Übersicht',
    tradeTab: 'Welthandel',
    liveMap: 'Live-Karte',
    resourceProjects: 'Projekte',
    esgSafety: 'ESG & Sicherheit',
    geologicalLibrary: 'Bibliothek',
    investorRelations: 'Investoren',
    inquireTerminal: 'Anfragen',
    qualifyAccess: 'ZUGANGSQUALIFIZIERUNG',
    liveIndex: 'Live LME/NYMEX Mineralindex:',
    companyTitle: 'MineX Gold, Silber & Bronze',
    companySubtitle: 'Strategische Operationen',
    stonesTab: 'Edelsteine',
    aiAssistantTitle: 'MINEX HILFE',
    heroTitlePre: 'Autonome Skalierung.',
    heroTitlePost: 'Souveräne Versorgung.',
    heroSubtitle: 'MineX ist ein führender Rohstoffproduzent, der erstklassiges Gold, Silber, Bronze und Lithium in stabilen Demokratien fördert.',
    exploreProjectsButton: 'Portfolio Erkunden',
    secureAccessButton: 'Datenzugriff Sichern',
    activeConcessions: 'Aktive Konzessionen',
    combinedReserves: 'Kombinierte Reserven',
    esgCarbonSc: 'ESG Carbon-Score',
    annualTarget: 'Jährliches Goldziel',
    investorPortal: 'Investorenportal',
    partnerPortal: 'Handelspartner',
    governmentPortal: 'Souveräne Regierungen',
    verifyRegistry: 'Anlagenregister Prüfen',
    submitSpecSheets: 'Spezifikationen Einreichen',
    inspectEsgPiles: 'ESG-Zertifikate Einsehen',
    operationsTitle: 'Echtzeit-Anlagen',
    operationsHeader: 'Interaktive Karte',
    operationsHeaderPost: ' & Touren',
    operationsDesc: 'Überwachen Sie unsere operativen Aktivitäten. Starten Sie virtuelle 360-Grad-Rundgänge.',
    tabLiveMap: 'Live-Betriebskarte',
    tabVirtualTour: 'Virtuelle 360°-Tour',
    satCoordinateSys: 'SATELLITEN-POSITIONS-SYSTEM',
    liveGpsStream: 'Live-GPS-Stream Aktiv',
    concessionHub: 'KONZESSIONSZENTRUM',
    telemetryStatus: 'Telemetriestatus',
    safetyIndex: 'Sicherheitsindex',
    headcountActive: 'Mitarbeiter Aktiv',
    environmentCore: 'Umweltschutz',
    surfaceWind: 'Oberflächenwind',
    powerAllocation: 'Energiezuweisung',
    mineVentilation: 'Belüftung',
    aquiferFluid: 'Grundwasserschutz',
    resourceType: 'Rohstoffart',
    launchTour: 'Tour Starten',
    tourStationDepot: 'AKTIVES TOUR-DEPOT',
    camReticulation: 'KAMERANETZWERK: AKTIV',
    projectStations: 'PROJEKTSTATIONEN:',
    prevNode: 'VORHERIGER KNOTEN',
    nextNode: 'NÄCHSTER KNOTEN',
    selectConcessionPano: 'KONZESSIONS-PANORAMA WÄHLEN',
    howToNavigateTour: 'Steuerung der Tour:',
    howToNavigateTourDesc: 'Nutzen Sie die Konsole, um zwischen Standorten zu wechseln. Klicken Sie auf gelbe Punkte für mehr Daten.',
    complianceWarning: 'Benötigen Sie eine Prüfung vor Ort? Kontaktieren Sie uns über das Terminal.',
    canadianCompliance: 'Konform mit Canadian NI 43-101',
    geoLibraryTitle: 'Bohrproben-Archiv',
    geoLibrarySubtitle: 'Bibliothek',
    geoLibrarySubtitlePost: ' & Kernregister',
    geoLibraryDesc: 'Zugriff auf geologische Berichte und Machbarkeitsstudien. Erfordert Autorisierung.',
    searchLibrary: 'Berichte oder Stichworte suchen...',
    statusLocked: 'GESICHERT - VERIFIKATION ERFORDERLICH',
    statusUnlocked: 'OFFENER ZUGANG - Download Bereit',
    lockedAction: 'Zugangsdaten Prüfen',
    unlockedAction: 'PDF Herunterladen',
    newsTitle: 'Operative Meilensteine',
    newsHeader: 'MineX ',
    newsHeaderPost: 'Newsroom',
    newsDesc: 'Erhalten Sie aktuelle Berichte und Bohrprobenanalysen direkt aus dem Hauptquartier.',
    readPrepText: 'Vollen Bericht lesen',
    filterAllNews: 'Alle Updates',
    bulletinSummary: 'Offizielle Bulletins',
    terminalHeader: 'Institutionelles Portal',
    terminalTitle: 'Anfrageterminal',
    terminalTitlePost: ' & Zugang',
    terminalDesc: 'Qualifizieren Sie sich für Datenräume oder planen Sie Gespräche mit der Geschäftsführung.',
    formAum: 'Verwaltetes Vermögen (AUM)',
    formSmelter: 'Schmelzkapazität (t/Jahr)',
    formAuthority: 'Behörde / Institution',
    formNotes: 'Details zum Vorhaben',
    formNotesDesc: 'Spezifizieren Sie die gewünschten Daten.',
    audienceLabel: 'STAKEHOLDER-MATRIZ WÄHLEN',
    nameLabel: 'Name',
    emailLabel: 'E-Mail-Adresse',
    orgLabel: 'Institution / Firma',
    projectFocusLabel: 'Gewünschter Fokus',
    selectProjectPlaceholder: '-- Fokus auswählen --',
    btnVerifyAccess: 'Datenzugriff Autorisieren',
    fileSecurityInfo: 'SICHERHEIT: Das Absenden startet die verschlüsselte Zustellung des Tokens.',
    verifiedRegistryTitle: 'AUTHENTIFIZIERUNG LÄUFT',
    verifiedRegistrySuccess: 'Zugriff gewährt! Ein temporärer Schlüssel wurde gesendet an ',
    accessTargetDoc: 'GESICHERTE DATEI:',
    sovereignMeetingCal: 'Konzessionsgespräche',
    coordinateMeeting: '1-on-1 Koordinationsgespräche vereinbaren',
    selectFocusSlot: 'Slot wählen',
    scheduleBriefing: 'Sitzung Buchen',
    briefingSlotHeld: 'Sitzungszeit Reserviert',
  },
  hi: {
    overview: 'अवलोकन',
    tradeTab: 'वैश्विक व्यापार',
    liveMap: 'लाइव मानचित्र',
    resourceProjects: 'परियोजनाएं',
    esgSafety: 'ईएसजी और सुरक्षा',
    geologicalLibrary: 'पुस्तकालय',
    investorRelations: 'निवेशक',
    inquireTerminal: 'पूछताछ टर्मिनल',
    qualifyAccess: 'पहुंच सत्यापन',
    liveIndex: 'लाइव एलएमई/नाइमेक्स सूचकांक:',
    companyTitle: 'MineX गोल्ड, सिल्वर और ब्रॉन्ज',
    companySubtitle: 'रणनीतिक खनिज संचालन',
    stonesTab: 'बेचे गए रत्न',
    aiAssistantTitle: 'MineX सहायता',
    heroTitlePre: 'स्वायत्त उत्पादन।',
    heroTitlePost: 'सॉवरेन आपूर्ति।',
    heroSubtitle: 'MineX एक प्रीमियम संसाधन कंपनी है जो दुनिया के सबसे स्थिर लोकतंत्रों में प्रमुख स्वर्ण, रजत और कांस्य भंडार का खनन करती है।',
    exploreProjectsButton: 'पोर्टफोलियो देखें',
    secureAccessButton: 'सुरक्षित भू-डेटा पहुंच',
    activeConcessions: 'सक्रिय क्षेत्र',
    combinedReserves: 'कुल स्वर्ण भंडार',
    esgCarbonSc: 'ईएसजी कार्बन स्कोर',
    annualTarget: 'वार्षिक लक्ष्य',
    investorPortal: 'निवेशक पोर्टल',
    partnerPortal: 'व्यापार भागीदार',
    governmentPortal: 'सॉवरेन सरकारें',
    verifyRegistry: 'वैश्विक संपत्ति सत्यापन',
    submitSpecSheets: 'विनिर्देश जमा करें',
    inspectEsgPiles: 'ईएसजी प्रमाणपत्र जांचें',
    operationsTitle: 'सक्रिय संपत्तियां',
    operationsHeader: 'इंटरएक्टिव मानचित्र',
    operationsHeaderPost: ' और टूर',
    operationsDesc: 'वैश्विक स्तर पर खनन गतिविधियों की निगरानी करें। वास्तविक 360° वर्चुअल टूर लॉन्च करें।',
    tabLiveMap: 'लाइव ऑपरेशन का नक्शा',
    tabVirtualTour: '360° वर्चुअल टूर',
    satCoordinateSys: 'सैटेलाइट पोजिशन कोऑर्डिनेट',
    liveGpsStream: 'लाइव जीपीएस स्ट्रीम सक्रिय',
    concessionHub: 'संचालन केंद्र',
    telemetryStatus: 'टेलीमेट्री स्थिति',
    safetyIndex: 'सुरक्षा सूचकांक',
    headcountActive: 'सक्रिय कर्मचारी',
    environmentCore: 'पर्यावरण पर्यावरण',
    surfaceWind: 'सतही हवा',
    powerAllocation: 'बिजली आवंटन',
    mineVentilation: 'हवा का प्रवाह',
    aquiferFluid: 'जल संरक्षण दर',
    resourceType: 'खनिज का प्रकार',
    launchTour: 'टूर शुरू करें',
    tourStationDepot: 'सक्रिय टूर स्टेशन',
    camReticulation: 'कैमरा नेटवर्क: सक्रिय',
    projectStations: 'परियोजना स्टेशन:',
    prevNode: 'पिछला नोड',
    nextNode: 'अगला नोड',
    selectConcessionPano: 'पैनोरमा चुनें',
    howToNavigateTour: 'नेविगेट करने का तरीका:',
    howToNavigateTourDesc: 'कंसोल का उपयोग करकेConcession स्विच करें। पीली जानकारी बटन पर क्लिक करें।',
    complianceWarning: 'क्या आपको ऑन-साइट जांच की आवश्यकता है? पूछताछ टर्मिनल में फॉर्म भरें।',
    canadianCompliance: 'कनाडाई एनआई 43-101 नियम के तहत प्रमाणित',
    geoLibraryTitle: 'ड्रिलिंग डेटा और खनिज परीक्षण',
    geoLibrarySubtitle: 'पुस्तकालय',
    geoLibrarySubtitlePost: ' और रजिस्टर',
    geoLibraryDesc: 'विस्तृत ड्रिलिंग परिणाम और खनिज रिपोर्ट प्राप्त करें। डाउनलोड करने के लिए क्रेडेंशियल आवश्यक हैं।',
    searchLibrary: 'रिपोर्ट या कीवर्ड खोजें...',
    statusLocked: 'सुरक्षित - क्रेडेंशियल सत्यापन आवश्यक',
    statusUnlocked: 'खुली पहुंच - डाउनलोड के लिए तैयार',
    lockedAction: 'क्रेडेंशियल सत्यापित करें',
    unlockedAction: 'पीडीएफ डाउनलोड करें',
    newsTitle: 'ऑपरेशनल अपडेट और समाचार',
    newsHeader: 'MineX ',
    newsHeaderPost: 'न्यूज़रूम',
    newsDesc: 'कंपनी मुख्यालय से सीधे जारी की गई तिमाही रिपोर्ट और ड्रिलिंग परिणाम देखें।',
    readPrepText: 'पूर्ण बुलेटिन पढ़ें',
    filterAllNews: 'सभी अपडेट',
    bulletinSummary: 'आधिकारिक बुलेटिन',
    terminalHeader: 'संस्थागत पोर्टल',
    terminalTitle: 'पूछताछ टर्मिनल',
    terminalTitlePost: ' और एक्सेस कॉरिडोर',
    terminalDesc: 'निजी डेटा रूम और ड्रिलिंग रिपोर्ट प्राप्त करने के लिए पंजीकरण करें।',
    formAum: 'प्रबंधित संपत्ति (AUM)',
    formSmelter: 'खनिज शोधन क्षमता (टन/वर्ष)',
    formAuthority: 'विभाग या एजेंसी',
    formNotes: 'पूछताछ विवरण और परियोजना ध्यान',
    formNotesDesc: 'आवश्यक डेटा और समय अवधि निर्दिष्ट करें।',
    audienceLabel: 'हितधारक विवरण दर्ज करें',
    nameLabel: 'आधिकारिक नाम',
    emailLabel: 'व्यावसायिक ईमेल',
    orgLabel: 'संस्था का नाम',
    projectFocusLabel: 'परियोजना का ध्यान',
    selectProjectPlaceholder: '-- परियोजना चुनें --',
    btnVerifyAccess: 'सत्यापित करें और पहुंचें',
    fileSecurityInfo: 'सुरक्षा सूचना: भेजा गया प्रपत्र एन्क्रिप्टेड क्रेडेंशियल जनरेट करेगा।',
    verifiedRegistryTitle: 'सत्यापन सक्रिय है',
    verifiedRegistrySuccess: 'सुरक्षित संपर्कों के लिए पहुँच प्रदान की गई! ईमेल पर टोकन भेजा गया: ',
    accessTargetDoc: 'गैजेटेड फ़ाइल:',
    sovereignMeetingCal: 'आधिकारिक बैठकें',
    coordinateMeeting: '1-on-1 कॉल शेड्यूल करें',
    selectFocusSlot: 'स्लॉट चुनें',
    scheduleBriefing: 'बैठक बुक करें',
    briefingSlotHeld: 'बैठक का समय बुक कर लिया गया है',
  },
  ar: {
    overview: 'نظرة عامة',
    tradeTab: 'التجارة العالمية',
    liveMap: 'الخريطة المباشرة',
    resourceProjects: 'المشاريع',
    esgSafety: 'الحوكمة والسلامة',
    geologicalLibrary: 'المكتبة',
    investorRelations: 'المستثمرون',
    inquireTerminal: 'الاستفسارات',
    qualifyAccess: 'مؤهل الوصول',
    liveIndex: 'مؤشر المعادن LME/NYMEX المباشر:',
    companyTitle: 'ماين إكس للذهب والفضة والبرونز',
    companySubtitle: 'العمليات الاستراتيجية للموارد',
    stonesTab: 'الأحجار الكريمة',
    aiAssistantTitle: 'دعم ماين إكس',
    heroTitlePre: 'تكامل الإنتاج آلياً.',
    heroTitlePost: 'سلسلة إمداد سيادية.',
    heroSubtitle: 'ماين إكس هي رائدة استخراج الذهب والفضة والبرونز والنحاس عالي النقاء والليثيوم في البيئات الديمقراطية المستقرة.',
    exploreProjectsButton: 'استكشف محفظة الأصول',
    secureAccessButton: 'الوصول الآمن لبيانات الأرض',
    activeConcessions: 'الامتيازات النشطة',
    combinedReserves: 'الاحتياطيات المجتمعة',
    esgCarbonSc: 'مستوى استهلاك الكربون',
    annualTarget: 'الهدف السنوي للذهب',
    investorPortal: 'بوابة المستثمرين',
    partnerPortal: 'شركاء المعالجة والتوزيع',
    governmentPortal: 'الحكومات والبيئة السيادية',
    verifyRegistry: 'التحقق من سجل الأصول',
    submitSpecSheets: 'إرسال وثائق التعدين',
    inspectEsgPiles: 'مراجعة شهادات المعايرة البيئية',
    operationsTitle: 'أصول التشغيل والقياسات',
    operationsHeader: 'الخريطة التفاعلية',
    operationsHeaderPost: ' والجولات',
    operationsDesc: 'مراقبة خط مبيعات التعدين في البيئات الجوفية. تفعيل جولات افتراضية 360 درجة.',
    tabLiveMap: 'خريطة البث المباشر للأصول',
    tabVirtualTour: 'جولة افتراضية بفتحة 360°',
    satCoordinateSys: 'منظومة تحديد إحداثيات الساتل',
    liveGpsStream: 'مؤشر تتبع GPS المباشر فعال',
    concessionHub: 'مركز الامتياز الرئيسي',
    telemetryStatus: 'حالة القياس الإلكتروني',
    safetyIndex: 'مؤشر السلامة العضوية',
    headcountActive: 'الكوادر البشرية النشطة',
    environmentCore: 'المحيط البيئي المركزي',
    surfaceWind: 'سرعة الرياح في السطح',
    powerAllocation: 'تخصيص الطاقة الكهربائية',
    mineVentilation: 'تدفق تهوية الأنفاق',
    aquiferFluid: 'كميات تدوير المياه الجوفية',
    resourceType: 'نوع الخام المستخرج',
    launchTour: 'بدء الجولة الافتراضية',
    tourStationDepot: 'محطة الرصد الفعالة',
    camReticulation: 'شبكة الكاميرا: متصلة',
    projectStations: 'محطات القياس الميدانية:',
    prevNode: 'النقطة السابقة',
    nextNode: 'النقطة التالية',
    selectConcessionPano: 'اختر منظور امتياز التعدين',
    howToNavigateTour: 'طريقة التنقل في الجولة الافتراضية:',
    howToNavigateTourDesc: 'استخدم الأزرار لتغيير المواقع. اضغط على الدوائر الصفراء المضيئة لمشاهدة تحليل المواد الميتالورجية.',
    complianceWarning: 'هل تحتاج إلى زيارة تدقيق مادية للموقع؟ املأ البيانات في بوابة الاستفسارات.',
    canadianCompliance: 'معتمد تحت معيار كندا NI 43-101',
    geoLibraryTitle: 'سجلات الحفر وقراءات الاختبار',
    geoLibrarySubtitle: 'المكتبة الفنية',
    geoLibrarySubtitlePost: ' ودفاتر العينات',
    geoLibraryDesc: 'احصل على التقارير الجيولوجية وبيانات الحفر الرسمية. الملفات المؤمنة تتطلب توثيق الأهلية.',
    searchLibrary: 'البحث في التقارير أو كلمات البحث للامتيازات...',
    statusLocked: 'مؤمن - يتطلب رخصة دخول للشركاء',
    statusUnlocked: 'مفتوح للجميع - جاهز للتنزيل المباشر',
    lockedAction: 'توثيق البيانات والوصول للملف',
    unlockedAction: 'تنزيل ملف PDF للاستقصاء',
    newsTitle: 'أخبار العمليات المؤسسية والتقارير',
    newsHeader: 'أخبار ',
    newsHeaderPost: 'ماين إكس التعدينية',
    newsDesc: 'تابع البيانات المالية وبحوث الحفر الأفقية الصادرة عن مكاتبنا الرئيسية بشكل دوري.',
    readPrepText: 'قراءة البيان الصحفي بالكامل',
    filterAllNews: 'جميع الأخبار والمنشورات',
    bulletinSummary: 'المنشورات الحكومية الرسمية',
    terminalHeader: 'البوابة الاستثمارية الكبرى',
    terminalTitle: 'محطة الاستفسارات',
    terminalTitlePost: ' وبوابات التصريح الآمن',
    terminalDesc: 'استوف بيانات التأهيل للوصول للغرف السرية للنتائج الميتالورجية أو حجز لقاءات مع الإدارة.',
    formAum: 'حجم الأصول المدارة (AUM)',
    formSmelter: 'الاستيعاب السنوي للتكرير الفني (طن/سنة)',
    formAuthority: 'الهيئة التنظيمية / الوزارة المعنية',
    formNotes: 'تفاصيل الاستفسار والمنشآت المستهدفة',
    formNotesDesc: 'حدد الوثائق الجيولوجية المطلوبة ومجالات العمليات.',
    audienceLabel: 'اختر موقعك في الهيكل الاستثماري',
    nameLabel: 'الاسم الرسمي الكامل',
    emailLabel: 'البريد الإلكتروني المعتمر',
    orgLabel: 'المؤسسة أو الكيان القانوني للمنشأة',
    projectFocusLabel: 'المنشأة الجغرافية المركزة',
    selectProjectPlaceholder: '-- اختر المركز المطلوب --',
    btnVerifyAccess: 'إرسال وتوثيق رخصة المرور',
    fileSecurityInfo: 'أمان البيانات: جميع البيانات المرسلة محمية بنظام تشفير SSL وسترسل الأكواد المؤقتة لبريدك مباشرة.',
    verifiedRegistryTitle: 'نظام المصادقة المشتركة نشط',
    verifiedRegistrySuccess: 'تم تأكيد صلاحية الوصول الفني! أرسلنا مفتاح المرور للبريد الإلكتروني: ',
    accessTargetDoc: 'الملف الفني المحمي:',
    sovereignMeetingCal: 'تقويم المقابلات الاستراتيجية',
    coordinateMeeting: 'طلب اتصال شخصي مباشر لمراجعة القوانين أو الاستثمار',
    selectFocusSlot: 'اختر الوقت المتاح',
    scheduleBriefing: 'تأكيد الحجز والاستفسار',
    briefingSlotHeld: 'تم تثبيت المقابلة بنجاح في الجدول المعتمد',
  },
  pt: {
    overview: 'Visão Geral',
    tradeTab: 'Comércio Global',
    liveMap: 'Mapa Operacional',
    resourceProjects: 'Projetos de Recursos',
    esgSafety: 'ESG e Segurança',
    geologicalLibrary: 'Biblioteca',
    investorRelations: 'Investidores',
    inquireTerminal: 'Consultas',
    qualifyAccess: 'REQUISITO DE ACESSO',
    liveIndex: 'Índice de Metais LME/NYMEX:',
    companyTitle: 'MineX Ouro, Prata e Bronze',
    companySubtitle: 'Operações Estratégicas de Recursos',
    stonesTab: 'Gemas Processadas',
    aiAssistantTitle: 'SUPORTE MINEX AI',
    heroTitlePre: 'Escala de mineração autônoma.',
    heroTitlePost: 'Soberania de abastecimento.',
    heroSubtitle: 'A MineX é uma líder de mercado na produção sustentável de ouro, prata, bronze, cobre e lítio em jurisdições estáveis da OCDE.',
    exploreProjectsButton: 'Explorar Portfólio',
    secureAccessButton: 'Acesso Seguro a Dados',
    activeConcessions: 'Concessões Ativas',
    combinedReserves: 'Reservas Totais',
    esgCarbonSc: 'Classificação de Carbono',
    annualTarget: 'Metas Anuais',
    investorPortal: 'Portal de Investidores',
    partnerPortal: 'Parceiros de Refino',
    governmentPortal: 'Governo e Sustentabilidade',
    verifyRegistry: 'Verificar Registro de Ativos',
    submitSpecSheets: 'Enviar Especificações Técnicas',
    inspectEsgPiles: 'Verificar Licenciamento Ambiental',
    operationsTitle: 'Ativos em Tempo Real',
    operationsHeader: 'Mapa Interativo',
    operationsHeaderPost: ' & Visitas',
    operationsDesc: 'Monitore operações no solo e no subsolo. Faça passeios virtuais de 360° em alta fidelidade.',
    tabLiveMap: 'Mapa de Operações em Tempo Real',
    tabVirtualTour: 'Visita Virtual Interactiva 360°',
    satCoordinateSys: 'SISTEMA DE COORDENADAS SATECOOR',
    liveGpsStream: 'Transmissão de GPS Ativa',
    concessionHub: 'CENTRO OPERACIONAL DE ATIVOS',
    telemetryStatus: 'Status da Telemetria',
    safetyIndex: 'Taxa de Segurança',
    headcountActive: 'Mão de Obra em Atividade',
    environmentCore: 'Indicadores Sanitários',
    surfaceWind: 'Velocidade do Vento',
    powerAllocation: 'Demanda Elétrica',
    mineVentilation: 'Exaustão d’Ar Direcionada',
    aquiferFluid: 'Recuperação Hidrológica',
    resourceType: 'Recurso Geológico Oficial',
    launchTour: 'Iniciar Passeio Virtual',
    tourStationDepot: 'STATION DE TOUR ATIVA',
    camReticulation: 'SINAL DE VÍDEO: CONECTADO',
    projectStations: 'ESTAÇÕES DE MONITORAMENTO:',
    prevNode: 'NÓ OPERACIONAL ANTERIOR',
    nextNode: 'NÓ OPERACIONAL SEGUINTE',
    selectConcessionPano: 'SELECIONAR PANORAMA DA CONCESSÃO',
    howToNavigateTour: 'Como navegar na plataforma:',
    howToNavigateTourDesc: 'Altere as localizações do menu superior. Clique no botão de informações amarelo para ler estatísticas das sondas.',
    complianceWarning: 'Precisa planejar inspeções pessoais no sítio? Registre seu interesse em nossa central.',
    canadianCompliance: 'Conforme NI 43-101 Regulamento Canadiano',
    geoLibraryTitle: 'Resultados de Sondagens e Geotecnia',
    geoLibrarySubtitle: 'Biblioteca Técnica',
    geoLibrarySubtitlePost: ' & Inventário d’Amostras',
    geoLibraryDesc: 'Consulte ensaios históricos e modelos estruturais de rochas. Arquivos restritos requerem login temporário.',
    searchLibrary: 'Buscar por relatórios, sondas ou palavras-chave...',
    statusLocked: 'RESTRETO - REQUER AUTORIZAÇÃO DE PARCEIROS',
    statusUnlocked: 'SINAL ABERTO - Pronto para download',
    lockedAction: 'Validar Credenciais e Carregar',
    unlockedAction: 'Efetuar Download PDF das Sondagens',
    newsTitle: 'Comunicados de Mercado e Divulgações',
    newsHeader: 'Notícias da ',
    newsHeaderPost: 'MineX Mining',
    newsDesc: 'Fique atualizado com os lucros operacionais e novas valorações geofísicas enviados do escritório corporativo.',
    readPrepText: 'Ler documento societário integral',
    filterAllNews: 'Compilação de Atualizações',
    bulletinSummary: 'Diários Oficiais',
    terminalHeader: 'Linha Direta de Fundos e Indústria',
    terminalTitle: 'Terminal de Consulta',
    terminalTitlePost: ' e Licenciamento Seguro',
    terminalDesc: 'Inscreva sua instituição na central para acesso facilitado a dados de testes de pureza d\'ouro.',
    formAum: 'Ativos sob Gestão (AUM)',
    formSmelter: 'Capacidade de Refinação Autorizada (t/ano)',
    formAuthority: 'Órgão Estatal / Agência de Regulação',
    formNotes: 'Escopo do Interesse Operacional',
    formNotesDesc: 'Descreva os conjuntos de dados técnicos requeridos e prazos.',
    audienceLabel: 'CATEGORIZE SEU PERFIL INSTITUCIONAL',
    nameLabel: 'Nome Oficial Corporativo',
    emailLabel: 'Endereço Eletrônico Funcional',
    orgLabel: 'Razão Social da Instituição',
    projectFocusLabel: 'Unidade Mineira Identificada',
    selectProjectPlaceholder: '-- Identificar unidade --',
    btnVerifyAccess: 'Aprovar Permissão e Emitir Licença',
    fileSecurityInfo: 'POLÍTICA DE DADOS: O envio de informações opera em redes criptografadas SSL com entrega direta à sua caixa d\'entrada.',
    verifiedRegistryTitle: 'PROCESSAMENTO DE LICENCIAMENTO',
    verifiedRegistrySuccess: 'Autorização concedida com êxito! O link do token seguro foi expedido para: ',
    accessTargetDoc: 'ARQUIVO TÉCNICO PROTEGIDO:',
    sovereignMeetingCal: 'Agendamento de Diálogos Executivos',
    coordinateMeeting: 'Requisitar reuniões pessoais para discutir parcerias',
    selectFocusSlot: 'Escolher intervalo horário',
    scheduleBriefing: 'Verificar Reserva de Agenda',
    briefingSlotHeld: 'Entrevista agendada com êxito no sistema',
  },
  ja: {
    overview: '概要',
    tradeTab: 'グローバル貿易',
    liveMap: 'リアルタイム鉱区マップ',
    resourceProjects: '資源開発ポートフォリオ',
    esgSafety: 'ESGと安全',
    geologicalLibrary: '地質資料館',
    investorRelations: '投資家窓口',
    inquireTerminal: '問い合わせ端末',
    qualifyAccess: '公式アクセス申請',
    liveIndex: '現在LME/NYMEX市況インデックス:',
    companyTitle: 'MineX 金・銀・ブロンズ',
    companySubtitle: '金・銀・青銅 戦略的鉱山開発会社',
    stonesTab: '製品鉱石レジストリ',
    aiAssistantTitle: 'MINEX地質情報システム',
    heroTitlePre: '最先端オートメーション開拓。',
    heroTitlePost: '鉱物資源の自立。',
    heroSubtitle: 'MineXは安定したOECD加盟国を中心に、高純度金、銀、ブロンズ、高純度銅、低エミッション型リチウムの鉱脈を保有・開発する世界的資源企業です。',
    exploreProjectsButton: '保有資産明細を閲覧',
    secureAccessButton: '地質情報データベースを保護',
    activeConcessions: '稼働中鉱区数',
    combinedReserves: '総ゴールド等価埋蔵量',
    esgCarbonSc: 'ESG二酸化炭素評価指標',
    annualTarget: '年間採掘目標',
    investorPortal: '機関投資家様向けポータル',
    partnerPortal: 'オフテイク・製錬パートナー専用',
    governmentPortal: '政府規制当局・環境監理用',
    verifyRegistry: '世界資産レジストリを検証',
    submitSpecSheets: '冶金技術スペックを提示',
    inspectEsgPiles: '環境保護活動証明書を閲覧',
    operationsTitle: '稼働資産・リアルタイムテレメトリ状況',
    operationsHeader: '双方向インタラクティブ地図',
    operationsHeaderPost: 'および現場バーチャル巡回',
    operationsDesc: '現在のプロジェクト状況を監視します。坑道、化学分析ラボ、浮選精錬室の360°リアルタイム画像を切り替えます。',
    tabLiveMap: '衛星リアルタイム連動型マップ',
    tabVirtualTour: '現場パノラマ・巡回映像システム',
    satCoordinateSys: 'GPS3次元静止衛星測位システム',
    liveGpsStream: 'リアルタイムGPSストリームオンライン',
    concessionHub: '採掘サイトハブ',
    telemetryStatus: '機材・環境データ計測ステータス',
    safetyIndex: '労働災害防止評価',
    headcountActive: '現在現場作業人数',
    environmentCore: '核心環境指数',
    surfaceWind: '坑外風速',
    powerAllocation: '主要受電割合',
    mineVentilation: '坑内主扇風量',
    aquiferFluid: '地下帯水層保護回収率',
    resourceType: '主要採掘資源品目',
    launchTour: 'バーチャル巡回を開始',
    tourStationDepot: '巡回ポイントコントロールデッキ',
    camReticulation: 'ビデオリンク：高画質接続',
    projectStations: '観測観測装置一覧:',
    prevNode: '前の観測点へ',
    nextNode: '次の観測点へ',
    selectConcessionPano: '巡回対象とする鉱区を選択',
    howToNavigateTour: 'パノラマシステムの操作方法:',
    howToNavigateTourDesc: 'メニューからサイトを切り替えることができます。パノラマ画像中に表示される「i」ボタンをクリックすると冶金機材分析を参照できます。',
    complianceWarning: '現地監査やコア岩石の実物査定をご希望の場合、インクワイアリ端末にて事業者登録を完了してください。',
    canadianCompliance: 'カナダ NI 43-101 資源開示基準に準拠',
    geoLibraryTitle: '国家承認ボーリング試錐台帳',
    geoLibrarySubtitle: '技術ライブラリ',
    geoLibrarySubtitlePost: '＆試錐サンプル保管庫',
    geoLibraryDesc: '過去の全試錐サンプル、岩石学的データ、環境アセスメントを公開しています。機密ドキュメント取得には一時コードの認証が必要です。',
    searchLibrary: '報告書名、ドリルホール番号、キーワードで検索...',
    statusLocked: '重要機密書面 - パートナー様認証が必要',
    statusUnlocked: 'オープン書庫 - 即時ダウンロード可能',
    lockedAction: '認証を行って書面を開く',
    unlockedAction: '試錐PDF資料をダウンロード',
    newsTitle: '企業公式プレスリリース＆進捗発表状況',
    newsHeader: 'MineX ',
    newsHeaderPost: 'ニュースルーム配信',
    newsDesc: '経営状況報告、主要試験孔高品位交差情報、国際的メーカーとの購入契約締結を即時配信します。',
    readPrepText: 'ニュース詳細全文を参照',
    filterAllNews: '配信リスト一覧',
    bulletinSummary: '公式広報レポート',
    terminalHeader: '投資ファンド・共同精錬ビジネス回線',
    terminalTitle: '問い合わせ用ターミナル',
    terminalTitlePost: 'および特別アクセスゲート',
    terminalDesc: '地質データの詳細要求や、幹部クラスとの戦略会議調整を受け付けるポータルです。安全にご利用いただけます。',
    formAum: '機関投資運用資産規模 (AUM)',
    formSmelter: '製錬容量・実績 (年間換算/トン)',
    formAuthority: '管轄官庁もしくは鑑定会社名',
    formNotes: '質問詳細および対象プロジェクト範囲',
    formNotesDesc: '必要とされる冶金パラメーターや提携内容を明記してください。',
    audienceLabel: 'お客様の事業者・投資者属性を設定',
    nameLabel: 'ご担当者様本名(フルネーム)',
    emailLabel: '所属企業の公的メールアドレス',
    orgLabel: '法人または所属機関の正式名称',
    projectFocusLabel: '関連する調査指定鉱区',
    selectProjectPlaceholder: '-- 調査対象を選択 --',
    btnVerifyAccess: '認証リクエスト・暗号鍵発行',
    fileSecurityInfo: '個人情報保護方針: 入力された内容は安全に処理され、ご指定いただいたアドレス宛てにアクセス権限コードが配信されます。',
    verifiedRegistryTitle: 'アクセス権限プロセッサ起動中',
    verifiedRegistrySuccess: 'アクセス許可が正常に発行されました。一時的な暗号解除キーをこちらに送信しました：',
    accessTargetDoc: '閲覧中・保護ドキュメント：',
    sovereignMeetingCal: '首脳会談カレンダー',
    coordinateMeeting: '1対1の法務協議・出資説明対話を予約',
    selectFocusSlot: '希望時間帯を選択',
    scheduleBriefing: 'ミーティング予約を入れる',
    briefingSlotHeld: 'システム上での面会時間枠を確保しました',
  },
  ru: {
    overview: 'Обзор',
    tradeTab: 'Мировая торговля',
    liveMap: 'Интерактивная карта',
    resourceProjects: 'Проекты ресурсов',
    esgSafety: 'Меры БЖД и Охрана труда',
    geologicalLibrary: 'Гео-библиотека',
    investorRelations: 'Инвесторам',
    inquireTerminal: 'Терминал Запросов',
    qualifyAccess: 'ПРОВЕРКА ДОСТУПА',
    liveIndex: 'Котировки на металлы LME/NYMEX:',
    companyTitle: 'MineX Золото, Серебро и Бронза',
    companySubtitle: 'Стратегическое Управление Недрами',
    stonesTab: 'Регистр Минералов',
    aiAssistantTitle: 'ПОДДЕРЖКА MINEX AI',
    heroTitlePre: 'Автономная добыча.',
    heroTitlePost: 'Стабильность поставок.',
    heroSubtitle: 'MineX — высокотехнологичный недропользователь, добывающий премиальное золото, серебро, бронзу и литий в развитых юрисдикциях.',
    exploreProjectsButton: 'Исследовать Активы',
    secureAccessButton: 'Получить Безопасный Доступ',
    activeConcessions: 'Активные Лицензии',
    combinedReserves: 'Суммарные Запасы золота',
    esgCarbonSc: 'Показатель Carbon ESG',
    annualTarget: 'Годовые Ориентиры',
    investorPortal: 'Портал для Инвесторов',
    partnerPortal: 'Промышленные Покупатели',
    governmentPortal: 'Госнадзор и Экология',
    verifyRegistry: 'Проверить реестр активов',
    submitSpecSheets: 'Передать технические спецификации',
    inspectEsgPiles: 'Просмотреть экологические отчеты',
    operationsTitle: 'Операционный Мониторинг в Реальном Времени',
    operationsHeader: 'Интерактивная Карта',
    operationsHeaderPost: ' и 3D-экскурсии',
    operationsDesc: 'Следите за работами в шахтах и на поверхности. Запустите виртуальные круговые туры 360°.',
    tabLiveMap: 'Спутниковая интерактивная карта',
    tabVirtualTour: 'Панорамные туры по рудникам',
    satCoordinateSys: 'СПУТНИКОВАЯ СИСТЕМА ИДЕНТИФИКАЦИИ GPSКООРД',
    liveGpsStream: 'Трансляция телеметрии GPS активна',
    concessionHub: 'УПРАВЛЕНИЕ ЛИЦЕНЗИОННЫМИ УЧАСТКАМИ',
    telemetryStatus: 'Передача параметров датчиков',
    safetyIndex: 'Индекс защиты здоровья',
    headcountActive: 'Численность дежурной смены',
    environmentCore: 'Экологический профиль',
    surfaceWind: 'Скорость ветра на поверхности',
    powerAllocation: 'Загрузка энергосистемы',
    mineVentilation: 'Расход воздуха в шахте',
    aquiferFluid: 'Очистка сточных вод',
    resourceType: 'Основное полезное ископаемое',
    launchTour: 'Запустить 3D-тур',
    tourStationDepot: 'КОНТРОЛЬНЫЙ ПУНКТ НАБЛЮДЕНИЯ',
    camReticulation: 'ВИДЕОСВЯЗЬ: ПОДКЛЮЧЕНО',
    projectStations: 'СПИСОК ИЗМЕРИТЕЛЬНЫХ УЗЛОВ:',
    prevNode: 'К ПРЕДЫДУЩЕЙ КАМЕРЕ',
    nextNode: 'К СЛЕДУЮЩЕЙ КАМЕРЕ',
    selectConcessionPano: 'ВЫБРАТЬ ЛИЦЕНЗИОННЫЙ УЧАСТОК',
    howToNavigateTour: 'Как пользоваться системой панорам:',
    howToNavigateTourDesc: 'Переключайте участки на панели. Нажимайте на мерцающие желтые круги для чтения отчетов оборудования.',
    complianceWarning: 'Требуется выездной аудит или физическая проверка керна? Зарегистрируйте запрос в терминале.',
    canadianCompliance: 'Соответствует канадскому стандарту NI 43-101',
    geoLibraryTitle: 'Результаты официальных буровых испытаний',
    geoLibrarySubtitle: 'Геологический архив',
    geoLibrarySubtitlePost: ' и Описания Керна',
    geoLibraryDesc: 'Доступ к геофизическим моделям месторождений и паспортам испытаний. Секретные файлы требуют временного пин-кода.',
    searchLibrary: 'Поиск по шифрам скважин, отчетам или ключевым словам...',
    statusLocked: 'ЗАЩИЩЕНО - ТРЕБУЕТСЯ ОФИЦИАЛЬНАЯ ПРОВЕРКА',
    statusUnlocked: 'ОТКРЫТЫЙ ДОСТУП - Файл доступен',
    lockedAction: 'Проверить допуск и открыть',
    unlockedAction: 'Скачать геофизический PDF',
    newsTitle: 'Корпоративные релизы и операционные отчеты',
    newsHeader: 'Новости ',
    newsHeaderPost: 'MineX Group',
    newsDesc: 'Отслеживайте финансовые показатели компании и результаты разведочного бурения из офиса в Ванкувере.',
    readPrepText: 'Читать полный текст сообщения',
    filterAllNews: 'Все публикации',
    bulletinSummary: 'Официальные заявления',
    terminalHeader: 'Канал для Фондов и Лицензиаров',
    terminalTitle: 'Информационный терминал',
    terminalTitlePost: ' и Шлюз Безопасности',
    terminalDesc: 'Подайте заявку на подключение к закрытым хранилищам геологических моделей и протоколам извлечения чистого золота.',
    formAum: 'Капитал под управлением (AUM)',
    formSmelter: 'Мощность аффинажа (тонн/год)',
    formAuthority: 'Орган надзора / Государственное ведомство',
    formNotes: 'Цель запроса и требуемый объем данных',
    formNotesDesc: 'Опишите характер запрашиваемых параметров руды и сроки.',
    audienceLabel: 'УКАЖИТЕ СВОЙ СТАТУС В ПРОЕКТЕ',
    nameLabel: 'Полное официальное имя',
    emailLabel: 'Служебный адрес электронной почты',
    orgLabel: 'Наименование организации / фонда',
    projectFocusLabel: 'Целевой горный отвод',
    selectProjectPlaceholder: '-- Выбрать месторождение --',
    btnVerifyAccess: 'Запросить право доступа и выдать ключ',
    fileSecurityInfo: 'ЗАЩИТА СВЕДЕНИЙ: Данные обрабатываются в зашифрованных SSL сессиях. Временный пин-код доставляется на e-mail.',
    verifiedRegistryTitle: 'СЛУЖБА ПРОВЕРКИ СТАТУСА',
    verifiedRegistrySuccess: 'Допуск успешно подтвержден! Временный крипто-ключ отправлен по адресу: ',
    accessTargetDoc: 'ОГРАНИЧЕННЫЙ К ПРОСМОТРУ ФАЙЛ:',
    sovereignMeetingCal: 'График официальных встреч',
    coordinateMeeting: 'Согласовать прямые переговоры с руководством',
    selectFocusSlot: 'Выбрать время встречи',
    scheduleBriefing: 'Забронировать окно для доклада',
    briefingSlotHeld: 'Встреча успешно записана в календарь',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
